namespace: "front"
num_endpoint_workers: 2

rules:
  mapping:
    - path: ["front","networkAdRequest"]
      help: "Adcalls per minute"
      labels: ["network"]

common:
  interval: 10
  labels:
    dc: "TMK"

endpoints:
  - url: "http://smart25e/api/metrics"
